# -*- coding: utf-8 -*-
"""HEART.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1my5RlUxcjgfnTgbCtrc5kQLewqQqyEAU
"""

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

heart_df = pd.read_csv("/content/heart.csv")
heart_df

heart_df.sample(5)

# getting summary
heart_df.info()

heart_df.describe()                   #numeric

heart_df.describe(include= 'all')               #all

# checking null values
print(heart_df.isnull().sum())

# checking duplicacy
heart_df.duplicated().sum()

# unique values
heart_df.nunique()

coln = heart_df.select_dtypes(include= 'object').columns

"""heart_df"""

heart_df

for col in coln :
  print(col)
  unique_values = heart_df[col].unique()
  mapped_values = range(heart_df[col].nunique())
  # print(mapped_values)
  heart_df[col].replace(unique_values , mapped_values , inplace = True)
  print('*'*20)
  print()

# handling invalid terms
heart_df['Cholesterol'].value_counts()

heart_df

heart_df['Cholesterol'].replace(0 , np.nan , inplace = True)

from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute  , columns = heart_df.columns)

# checking 0 values
count = 0
for i in heart_df['Cholesterol']:
  if i == 0:
    count += 1
print(count)

# handle resting BP remove 0

heart_df['RestingBP'].replace(0 , np.nan , inplace = True)

from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=3)
after_impute = imputer.fit_transform(heart_df)
heart_df = pd.DataFrame(after_impute  , columns = heart_df.columns)

heart_df['RestingBP'].unique()
#

woldpeak = heart_df.columns
woldpeak = woldpeak.drop('Oldpeak')
heart_df[woldpeak] = heart_df[woldpeak].astype('int32')

heart_df.info()

heart_df.sample(1)

"""DATA VISUALISATION

"""

!pip install plotly

import plotly as px

heart_df.corr()

import plotly.express as px
px.line(heart_df.corr()["HeartDisease"][:-1].sort_values())

px.sunburst(heart_df, path= ['HeartDisease', 'Age'])

px.histogram(heart_df, x = 'Age' , color = 'HeartDisease')

px.pie (heart_df , names = 'HeartDisease' ,title ="Percentage of heart diseases class distributing" )

px.histogram(heart_df , x = 'Sex' , color = 'HeartDisease')

px.histogram(heart_df , x = 'ChestPainType' , color = 'HeartDisease')

heart_df['RestingBP'].unique()

px.sunburst(heart_df , path =  ['HeartDisease' , 'RestingBP' ])

px.histogram(heart_df , x = 'FastingBS' , color = 'HeartDisease')

px.sunburst (heart_df , path = ['HeartDisease' , 'MaxHR'])

px.violin(heart_df , x = 'HeartDisease' , y = 'MaxHR' , color = 'HeartDisease')

px.violin (heart_df , x = 'HeartDisease' , y = 'Oldpeak' , color = 'HeartDisease')

px.histogram(heart_df , x = 'ST_Slope' , color = 'HeartDisease')

px.histogram(heart_df , x = 'ExerciseAngina' , color = 'HeartDisease')

from sklearn.model_selection import train_test_split
X_train ,  X_test , Y_train , Y_test = train_test_split(
   heart_df.drop('HeartDisease' ,axis = 1),
   heart_df['HeartDisease'],
   test_size = 0.2 ,
   random_state = 42,
   stratify = heart_df['HeartDisease']
)

"""Model Training

"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

solver = ['liblinear' , 'newton-cg' , 'lbfgs' , 'sag' , 'saga']
best_solver = ''
test_score = np.zeros(6)

for i , n in enumerate(solver):
  lr = LogisticRegression(solver = n).fit(X_train , Y_train)
  test_score[i] = lr.score(X_test , Y_test)
  if lr.score(X_test , Y_test) == test_score.max():
    best_solver = n
print(best_solver)
lr = LogisticRegression(solver = best_solver)
lr.fit(X_train , Y_train)
lr_pred = lr.predict(X_test)
print("LogisticRegression : ",accuracy_score(Y_test , lr_pred))

import pickle
file = open('Logistic.pkl' , 'wb')
pickle.dump(lr , file)

from sklearn.svm import SVC
from sklearn.metrics import f1_score

kernels = {'linear':0 , 'poly':0 , 'rbf':0 , 'sigmoid':0}
best_kernel = ''
for i in kernels:
  svm = SVC(kernel=i)
  svm.fit(X_train , Y_train)
  svm_pred = svm.predict(X_test)
  kernels[i] = f1_score(Y_test , svm_pred , average = 'weighted')
  if kernels[i] == max(kernels.values()):
    best_kernel = i

print(best_kernel)
svm = SVC(kernel= best_kernel)
svm.fit(X_train , Y_train)
svm_pred = svm.predict(X_test)
print("SVM: " , f1_score(Y_test , svm_pred , average = 'weighted'))

"""Decision Tree Classifier"""

file = open('Svm.pkl' , 'wb')
pickle.dump(svm , file)

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

dtree= DecisionTreeClassifier(class_weight = 'balanced')
param_grid = { 'max_depth': [3,4,5,6,7,8],
              'min_samples_split': [2,3,4],
               'min_samples_leaf':[1,2,3,4],
               'random_state':[0,42]}
grid_search = GridSearchCV(estimator = dtree , param_grid = param_grid , cv= 5)

grid_search.fit(X_train , Y_train)
Ctree = DecisionTreeClassifier(**grid_search.best_params_ , class_weight = 'balanced')

Ctree.fit(X_train , Y_train)
dtc_pred = Ctree.predict(X_test)
print("Decision Tree Classifier: " , accuracy_score(Y_test , dtc_pred))

"""RANDOM FOREST CLASSIFIER"""

file = open('DecTree.pkl' , 'wb')
pickle.dump(dtree , file)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

rfc = RandomForestClassifier()
param_grid = {
    'n_estimators': [50,100.150,500],
    'max_depth': [3,4,5,6,7,8],
    'max_features' : ['sqrt' , 'log2' , None],
    'max_leaf_nodes' :[3,6,9]

}
grid_search = GridSearchCV(estimator = rfc , param_grid = param_grid )
grid_search.fit(X_train , Y_train)
rfc = RandomForestClassifier(**grid_search.best_params_)
rfc.fit(X_train , Y_train)
rfc_pred = rfc.predict(X_test)
print("Random Forest Classifier: " , accuracy_score(Y_test , rfc_pred))

file = open('Rfc.pkl' , 'wb')
pickle.dump(grid_search , file)

